### ISSUE TITLE
C/Python discrepancy: __parent__ as a class attribute fails in Python, works in C

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/ExtensionClass#24]
Given the following example, the first assertion passes in both versions, but the second one fails with the PURE_PYTHON implementation.
```python
# foo.py
from ExtensionClass import Base

class O(Base):
    __parent__ = None

assert O.__parent__ is None
assert O().__parent__ is None
```

```console
$ python /tmp/foo.py
$ PURE_PYTHON=1 python /tmp/foo.py
Traceback (most recent call last):
  File "/tmp/foo.py", line 7, in <module>
    assert O().__parent__ is None
  File "//python3.8/site-packages/ExtensionClass/__init__.py", line 255, in Base_getattro
    raise AttributeError(
AttributeError: ("'%.50s' object has not attribute '%s'", 'O', '__parent__')
```

This is true in both Python 2 and Python 3, and PyPy fails the same way CPython does. The logic in `Base_getattro` appears to be missing a step compared to the C implementation.

Context/use-case: Given `class O(Acquisition.Implicit, zope.container.contained.Contained)`, you can't put instances of `O` in a container; that raises an AttributeError trying to get the old_parent.

```pycon
>>> os.environ['PURE_PYTHON'] = '1'
>>> from zope.container.btree import BTreeContainer
>>> from Acquisition import Implicit
>>> from zope.container.contained import Contained
>>> class O(Implicit, Contained):
...     pass
...
>>> BTreeContainer()['key'] = O()
Traceback (most recent call last):
  File "//python3.8/site-packages/Acquisition/__init__.py", line 786, in __getattribute__
    return super(_Acquirer, self).__getattribute__(name)
  File "///site-packages/ExtensionClass/__init__.py", line 255, in Base_getattro
    raise AttributeError(
AttributeError: ("'%.50s' object has not attribute '%s'", 'O', '__parent__')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Sources/zope.container/src/zope/container/btree.py", line 84, in __setitem__
    setitem(self, self._setitemf, key, value)
  File "//zope.container/src/zope/container/contained.py", line 575, in setitem
    object, event = containedEvent(object, container, name)
  File "//zope.container/src/zope/container/contained.py", line 311, in containedEvent
    oldparent = object.__parent__
  File "//python3.8/site-packages/Acquisition/__init__.py", line 792, in __getattribute__
    _reraise(AttributeError, AttributeError(name), tb)
  File "//python3.8/site-packages/Acquisition/__init__.py", line 74, in _reraise
    raise value.with_traceback(tb)
  File "//python3.8/site-packages/Acquisition/__init__.py", line 786, in __getattribute__
    return super(_Acquirer, self).__getattribute__(name)
  File "//python3.8/site-packages/ExtensionClass/__init__.py", line 255, in Base_getattro
    raise AttributeError(
AttributeError: __parent__
```

**Comment by jamadden** [comment]
The issue seems to be that the Python version is using `None` as the value to mean "no attribute", even though that's a valid value; in C that's spelled `NULL`. Using a special marker object solves the issue, to a first approximation:

```patch
---------------------------------------------
modified: src/ExtensionClass/__init__.py
---------------------------------------------
@@ -223,14 +223,14 @@ class ExtensionClass(type):
 # to care or worry about using super(): it's always object.

 def Base_getattro(self, name):
-    descr = None
+    descr = marker = object()

     for base in type(self).__mro__:
         if name in base.__dict__:
             descr = base.__dict__[name]
             break

-    if descr is not None and inspect.isdatadescriptor(descr):
+    if descr is not marker and inspect.isdatadescriptor(descr):
         return descr.__get__(self, type(self))

     try:
@@ -245,16 +245,17 @@ def Base_getattro(self, name):
             if name == '__parent__' or not isinstance(descr, Base):
                 return descr

-    if descr is not None:
-        descr_get = getattr(descr, '__get__', None)
-        if descr_get is None:
+    if descr is not marker:
+        descr_get = getattr(descr, '__get__', marker)
+        if descr_get is marker:
             return descr

         return descr_get(self, type(self))

     raise AttributeError(
-            "'%.50s' object has not attribute '%s'",
-            type(self).__name__, name)
+        "'%.50s' object has no attribute '%s'" % (
+            type(self).__name__, name
+        ))


 def _slotnames(self):
```
